# pubspec.yaml
name: translator
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # свежий FlutterFire (июнь-2025)
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4       # ← 5-я ветка использует новый Pigeon-протокол
  cloud_firestore: ^5.0.0
 

  # Google Sign-In остаётся свежим
  google_sign_in: ^6.2.1


  http: ^1.4.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
